/// Flutter icons FixIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FixIcons
///      fonts:
///       - asset: fonts/FixIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FixIcons {
  FixIcons._();

  static const _kFontFam = 'FixIcons';
  static const String? _kFontPkg = null;

  static const IconData hazadous_dump_location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData how_to_sorting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
